UnityHPC/unity-web-portal

resources/mail/footer.php

The footer was throwing an error for users in emails, because an old `$BRANDING` array was left in. This is tested and working.

fixed footer lookup on mails

---

resources/lib/UnityGroup.php
webroot/admin/pi-mgmt.php
webroot/panel/groups.php
webroot/panel/pi.php

- Needed to add request date to requests displayed on `admin/pi-mgmt.php`, `panel/groups.php`, and `panel/pi.php`.
- Modified `getRequests()` in `resources/lib/UnityGroup.php` to return a tuple with the user object as the first element and the timestamp as the second element.
- #36

Adding request date to user/pi requests

---

config/branding/config.ini
webroot/index.php

add home page to content management

---

resources/lib/UnitySite.php
webroot/js/ajax/ssh_validate.php
webroot/panel/account.php
webroot/panel/modal/new_key.php

- ssh key validation done with `PublicKeyLoader`
- added ajax call for ssh key validation on textarea change
- added red box shadow to textarea and disabled "Add Key" button if key is not valid
- added ssh key validation code on the backend for both cases of paste and file import
- #17

ssh key validation

---

defaults/config.ini.default
resources/autoload.php
resources/init.php
resources/lib/UnityGroup.php
resources/lib/UnityLDAP.php
resources/lib/UnityOrg.php
resources/lib/UnityUser.php
resources/lib/UnityWebhook.php
webroot/admin/ajax/get_group_members.php
webroot/admin/pi-mgmt.php
webroot/admin/user-mgmt.php
webroot/panel/ajax/get_group_members.php
webroot/panel/groups.php
webroot/panel/modal/pi_search.php
webroot/panel/new_account.php
webroot/panel/pi.php
workers/update-ldap-cache.php

- Created new library UnityWebhook to send notifications to admins on slack channel
- Gets the template from the mail directory, converts into markdown format required by slack
- Delivered message looks like:
- #37

Added slack webhook notification functionality

---

resources/init.php
resources/lib/UnityGroup.php
resources/lib/UnitySQL.php
resources/lib/UnityUser.php
webroot/admin/content.php
webroot/admin/notices.php
webroot/admin/pi-mgmt.php
webroot/panel/account.php

- Added additional audit logs as per https://github.com/UnityHPC/unity-web-portal/issues/68#issuecomment-1492615022

Additional audit logs

---

defaults/config.ini.default
resources/init.php
resources/lib/UnityGroup.php
webroot/panel/account.php
webroot/panel/new_account.php

- Added a boolean config variable `send_pimesg_to_admins` to set whether PI request mails go to admins or not.
- #63

Made emailing admins for PI requests optional

---

resources/lib/UnityGroup.php
resources/lib/UnitySQL.php
resources/lib/UnityUser.php
resources/mail/account_deletion_request_admin.php
tools/docker-dev/sql/bootstrap.sql
webroot/admin/user-mgmt.php
webroot/panel/account.php
webroot/panel/groups.php

- Gave user option to request account deletion (only if user is not in any PI groups)
- Adds them to a new SQL table - `account_deletion_requests`
- Sends email to admins
- Updates user management for admins (graying and italicizing the users who have requested account deletion)
- #43

added option for account deletion requests

---

resources/lib/UnityGroup.php
resources/lib/UnityLDAP.php
resources/lib/UnityOrg.php
resources/lib/UnitySQL.php
resources/lib/UnityUser.php
tools/docker-dev/sql/bootstrap.sql

- Made new table `sitevars` (Structure: `id`, `name`, `value`)
- Initially maximum uid, gid, pigid need to be stored in the table with names as `MAX_UID`, `MAX_GID`, `MAX_PIGID`.
- Then, whenever a new user, group, or pi group is created, the id assigned is an increment of the maximum value by 1.
- #76

stored max id values in sitevars table

---

resources/lib/UnityPerms.php
resources/lib/UnitySQL.php
resources/lib/UnityUser.php
tools/docker-dev/sql/bootstrap.sql

Created UnityPerms Class

---

webroot/api/notices/index.php

Created JSON Schema to print Notices

---

webroot/panel/groups.php

https://github.com/UnityHPC/unity-web-portal/issues/99

trim PI request

---

tools/docker-dev/sql/bootstrap.sql

768 is the maximum length that can be used as the primary key in a mariaDB table. using 769, I get this error:
```
#1071 - Specified key was too long; max key length is 3072 bytes 
```

reduce size of data types

---

resources/lib/UnitySQL.php

https://github.com/UnityHPC/unity-web-portal/issues/121

site var not found is an error

---

test/functional/LoginShellSetTest.php
webroot/panel/account.php

* use JS instead of PHP for making the initial login shell selection
* inject PHP variables into JS on its own string declaration line
* use one `showOrHideCustomLoginBox` function for updates and initial state, rather than writing the same logic 3 times
* use value "Custom" everywhere rather than using "custom" internally and "Custom externally"

cleanup panel/account.php

---

webroot/panel/account.php

PI: ![image](https://github.com/user-attachments/assets/07c5dae8-fc96-4dfa-9947-e0489dcd8c8c)
non PI: ![image](https://github.com/user-attachments/assets/a43fa3de-e4a1-443b-9629-7354bf33b1c8)
non PI requested account deletion:

add closing slashes, indentation

---

CONTRIBUTING.md
defaults/config.ini.default
resources/lib/UnityUser.php
test/functional/LoginShellSetTest.php
webroot/panel/account.php

this is the fun alternative to https://github.com/UnityHPC/unity-web-portal/pull/200
Fixes a WSOD when a user tries to set their login shell with non ascii characters. Also avoids the LDAP warnings generated in testing: https://github.com/UnityHPC/unity-web-portal/actions/runs/14648366156/job/41108067187
It also grays out the submit button when there's no change.
https://github.com/user-attachments/assets/f076c765-f578-4191-9835-63ff704c3b7f

Remove custom shell

---

webroot/panel/account.php

PI: ![image](https://github.com/user-attachments/assets/3f781be2-c4f3-40d4-9174-db55a70b37da)
non PI: ![image](https://github.com/user-attachments/assets/e0ac0e38-bd4c-4d4b-941a-d039173dc305)
non PI with PI account request: ![image](https://github.com/user-attachments/assets/69ea8304-3866-4fcb-9624-ae0224b8d2bc)
non PI with account deletion request: ![image](https://github.com/user-attachments/assets/95e9b5a0-d7fe-442c-8bd5-447382a20e44)
non PI with account deletion request and PI account request: ![image](https://github.com/user-attachments/assets/c130c5cb-a006-4010-b52a-a4818895f495)

cleanup account page 3

---

webroot/css/global.css
webroot/panel/account.php

* added a `.code` CSS class so that any element can be code
* removed `width: 100%` from `<select>` and `<input type=select>`
* added extra padding (more left than right) to `<select>` and `<input type=select>`
* more left than right because the right has the downward arrow symbol
* modified the account settings login shell select to have the `code` class
before: 
https://github.com/user-attachments/assets/33817c19-7dd0-4f5e-b7e2-e85ac06cb092
after:
https://github.com/user-attachments/assets/937b734d-bb4c-4ebc-b950-03ce03c21801

prettify login shell selector

---

resources/lib/UnityGroup.php
webroot/admin/pi-mgmt.php
webroot/panel/pi.php

removed the "disband PI group" functionality from HTML, PHP HTTP API, and UnityGroup. also removed a stray `</table>` from the end of `pi.php`.
before: 
after: ![image](https://github.com/user-attachments/assets/e10c233c-310e-4312-9353-ee4d51b14daf)
pi mgmt:
before: ![image](https://github.com/user-attachments/assets/8450e447-4a98-40ed-9783-2c43ec25328b)
after: ![image](https://github.com/user-attachments/assets/2537974f-c8c7-41cc-afc7-2480b7b8efaa)

remove disband PI

---

resources/lib/UnitySQL.php
tools/docker-dev/sql/bootstrap.sql

remove "events", "sso_log"

---

resources/lib/UnityUser.php

Fatal error: Uncaught Error: Call to undefined function UnityWebPortal\lib\transliterator_transliterate() in /var/www/unity-web-portal/resources/lib/UnityUser.php:76 Stack trace: #0 /var/www/unity-web-portal/resources/lib/UnityGroup.php(143): UnityWebPortal\lib\UnityUser->init() #1 /var/www/unity-web-portal/webroot/admin/pi-mgmt.php(23): UnityWebPortal\lib\UnityGroup->approveGroup() #2 {main} thrown in /var/www/unity-web-portal/resources/lib/UnityUser.php on line 76

absolute transliterator

---

defaults/config.ini.default
resources/lib/UnityGroup.php
resources/lib/UnityLDAP.php
resources/lib/UnitySQL.php
resources/lib/UnitySite.php
resources/mail/group_join_request_cancelled.php
resources/mail/group_request_cancelled.php
resources/templates/header.php
test/functional/CancelRequestTest.php
test/phpunit-bootstrap.php
test/unit/UnityGithubTest.php
webroot/panel/new_account.php

Modify the new_account page to allow a user without an account to cancel a pending request for either a PI account or joining a group.

Add ability to cancel request, require confirmation of account policy, fix dubious redirect

---

resources/lib/UnityGroup.php
resources/lib/UnityOrg.php
resources/lib/UnitySQL.php
resources/lib/UnityUser.php
test/functional/NewUserTest.php
test/functional/PiBecomeRequestTest.php
test/functional/PiMemberApproveTest.php
test/functional/PiMemberDenyTest.php
test/functional/PiRemoveUserTest.php
tools/docker-dev/build.sh
tools/docker-dev/sql/bootstrap.sql
webroot/admin/ajax/get_group_members.php
webroot/admin/pi-mgmt.php
webroot/panel/account.php
webroot/panel/groups.php
webroot/panel/new_account.php
webroot/panel/pi.php

Problem:
When redis is flushed, the names/emails/orgs of all nonexistent users disappear. Any attempt to approve requests made by these users will result in a white screen of death because the portal doesn't know what name/email/org to write to LDAP.
Solution:
Any access to name/email/org for a nonexistent user is now an error. name/email/org are stored with each request.
Notes:
The request creations now have assertions that `$USER` and `$SSO` match. This is to prevent an admin from viewing as another user and accidentally submitting a request for that user with the admin's name/email/org.

Store user data in request

---

resources/init.php
resources/lib/UnitySSO.php
resources/lib/exceptions/SSOException.php
test/functional/InvalidEPPNTest.php
test/phpunit-bootstrap.php

Adds logging of the invalid eppn with a unique number shown in the log and to the user.

Show an error message to the user when eppn is invalid

---

resources/lib/UnityLDAP.php

Were passing the second argument as if it was the first. Added the default value for the second.

Fix ldap_escape calls to correct the argument list

---

README.md
tools/docker-dev/identity/Dockerfile
tools/docker-dev/identity/configure-unique.ldif
tools/docker-dev/identity/load-modules.ldif

closes https://github.com/UnityHPC/unity-web-portal/issues/290

Ldap unique

---

defaults/config.ini.default
deployment/overrides/phpunit/config/config.ini
deployment/overrides/worker/config/config.ini
resources/lib/UnitySite.php

This is only a slight improvement for https://github.com/UnityHPC/unity-web-portal/issues/306. In general, I think it makes sense for "forbidden" and "bad request" errors to also make an error popup and generate an error ID.
* moved the user-facing error message functionality from the shutdown function to `UnitySite::errorToUser`
* activated user-facing error message functionality in `badRequest`, `forbidden`
* extended `UnitySite::errorLog` to take new parameters `errorid`, `error`, `data`
* before, `errorid` was only printed from the shutdown function, and it was assumed that the reader would look at the previous message from `errorLog` to correlate it with the `errorid`
* `data` parameter is used by the shutdown function since `error_get_last` doesn't return a `Throwable` but just an …

improve logging
